In [51]:
import pandas as pd
import numpy as np
import seaborn as sns
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
import warnings
warnings.filterwarnings("ignore")

In [2]:
returns = pd.read_pickle("../Data/returns.pkl")
returns

905270    921795    904261    905261    916328    923024  \
date                                                                     
1990-01-02       NaN       NaN       NaN       NaN       NaN       NaN   
1990-01-03 -0.835165 -0.475059  5.000000 -0.810537  0.361421  0.000000   
1990-01-04 -0.797872 -1.272872  2.380952 -1.634321 -0.180060  3.454545   
1990-01-05 -2.546917  1.531023 -0.372093 -1.661475 -1.079730  1.054482   
1990-01-08  2.017423 -0.873016  0.000000  2.534319  0.000000  0.000000   
...              ...       ...       ...       ...       ...       ...   
2021-05-24       NaN       NaN       NaN       NaN  0.136600       NaN   
2021-05-25       NaN       NaN       NaN       NaN  0.946372       NaN   
2021-05-26       NaN       NaN       NaN       NaN -1.393581       NaN   
2021-05-27       NaN       NaN       NaN       NaN -0.907923       NaN   
2021-05-28       NaN       NaN       NaN       NaN  0.829804       NaN   

              936365    902355    912215    929813  ...    9660J1    69568X  \
date                                                ...                       
1990-01-02       NaN       NaN       NaN       NaN  ...       NaN       NaN   
1990-01-03 -3.030303  0.000000 -0.431034 -1.315789  ...       NaN       NaN   
1990-01-04 -1.562500  0.530612  0.225108  0.000000  ...       NaN       NaN   
1990-01-05 -3.174603  0.487211 -0.656531 -1.333333  ...       NaN       NaN   
1990-01-08  0.000000  1.010101  0.434783  3.405405  ...       NaN       NaN   
...              ...       ...       ...       ...  ...       ...       ...   
2021-05-24  0.349877       NaN       NaN       NaN  ...  0.376702  4.400221   
2021-05-25  0.542355       NaN       NaN       NaN  ...  0.230947 -0.288569   
2021-05-26  0.616491       NaN       NaN       NaN  ...  1.296083  2.388001   
2021-05-27  0.102119       NaN       NaN       NaN  ...  0.056867  1.893011   
2021-05-28  2.116807       NaN       NaN       NaN  ... -0.312589 -0.892462   

              543755    77463M    29235J    131745    69487D    68157P  \
date                                                                     
1990-01-02       NaN       NaN       NaN       NaN       NaN       NaN   
1990-01-03       NaN       NaN       NaN       NaN       NaN       NaN   
1990-01-04       NaN       NaN       NaN       NaN       NaN       NaN   
1990-01-05       NaN       NaN       NaN       NaN       NaN       NaN   
1990-01-08       NaN       NaN       NaN       NaN       NaN       NaN   
...              ...       ...       ...       ...       ...       ...   
2021-05-24  1.590198 -0.991004  1.682900  3.364703  2.271817  0.634962   
2021-05-25  0.449063 -1.661106  0.439588 -0.548765  0.185928  0.727530   
2021-05-26 -0.166049  3.255613  2.317760  4.702784  0.673960  2.336242   
2021-05-27 -0.063971 -0.510347  1.044185 -0.275482  1.979237  1.876893   
2021-05-28 -0.409679  0.519992  0.160551 -1.549363  0.570831  0.766354   

              9110RA    292703  
date                            
1990-01-02       NaN       NaN  
1990-01-03       NaN       NaN  
1990-01-04       NaN       NaN  
1990-01-05       NaN       NaN  
1990-01-08       NaN       NaN  
...              ...       ...  
2021-05-24  4.859794  1.204016  
2021-05-25  1.884279 -0.498203  
2021-05-26 -0.429666 -1.520393  
2021-05-27  1.247655  2.369727  
2021-05-28 -0.444733  1.742926  

[7914 rows x 1238 columns]

In [3]:
returns = returns.iloc[1:]

In [4]:
# dropping columns with all NaN
drop_columns = []

for col in returns.columns:
    if returns[col].isnull().all() == True:
        drop_columns.append(col)
        
returns.drop(columns=drop_columns, inplace=True)

In [8]:
def get_investable(t, n_rows):
    "Find stocks in investable universe at time t\
    (stocks in the S&P500 that have prices recorded for the last n_rows days)"
    
    df_investable = returns.copy(deep = True).sort_index(ascending = False)
    
    most_recent = t
    least_recent = t + pd.DateOffset(-n_rows)
    
    #take n_rows worth of data upto time specified
    df_investable = df_investable[most_recent+pd.DateOffset(-1):least_recent]
    
    #find all stocks that exist in the S&P at this time period
    investable_universe = []
    for col in df_investable.columns:
        if ~df_investable[col].iloc[:n_rows].isna().any():
            investable_universe.append(col)
        
    df_investable = df_investable[investable_universe]
    
    return df_investable

In [60]:
t = pd.to_datetime("2020-02-25")

get_investable(t, 80)

916328    936365    905271    905113    905802    905425  \
date                                                                     
2020-02-24 -3.224700 -7.807808 -3.702396 -1.195098 -6.519714 -1.641923   
2020-02-21 -1.141759 -6.966998 -0.168363 -0.682511 -0.463535 -0.654425   
2020-02-20 -1.007162 -2.767402 -0.164178 -1.085978  1.809029 -1.082126   
2020-02-19  0.540054  3.533134  0.031282  2.682395  3.974485 -0.795553   
2020-02-18 -0.869953  2.856626 -0.105465 -0.539684  1.325820  0.549345   
2020-02-14  1.105097  1.430405  0.443346  1.244447  0.583431  0.884784   
2020-02-13 -0.123888  1.187604  0.306966  0.426659  2.075889  1.041360   
2020-02-12 -0.426152  0.167286  0.669546  2.467058  4.647436 -0.420661   
2020-02-11  0.985277  2.946804  0.278098  1.169012  2.202002  0.294349   
2020-02-10  0.489359  5.087472  0.716229  1.118313 -0.901713  0.572331   
2020-02-07 -1.788309  0.831306 -0.454075 -0.318264 -2.770472 -0.889976   
2020-02-06 -0.100491 -1.043339  0.311651  0.447815 -3.844208  0.127301   
2020-02-05  1.507424  0.788675  1.291028  2.559186  2.843766 -0.729076   
2020-02-04  1.343901  2.977926  1.678943  1.397075  2.197413 -1.295337   
2020-02-03 -0.091806  2.170213  1.801349  0.367213 -0.247481  0.000000   
2020-01-31 -2.265590 -3.649036 -1.118429 -1.642245 -3.398224  0.115274   
2020-01-30  0.022437  2.673121  1.744848 -2.246979  1.279834  1.254742   
2020-01-29 -0.446728 -5.976648  0.346796 -1.016922 -6.922086  0.606713   
2020-01-28 -0.055810  2.578157  1.276395  2.608407 -0.048270  0.402830   
2020-01-27 -0.896018 -2.164846 -4.295962  5.359256 -3.508772 -0.371966   
2020-01-24 -0.363717 -2.630052  2.806692 -1.422588 -3.186532  1.178568   
2020-01-23 -1.230133  0.544429 -0.315073  2.392574 -0.997024  0.970000   
2020-01-22  2.373788  0.744368  0.362594 -1.904584 -1.883487  0.664385   
2020-01-21  0.820225  0.235618  0.075949  0.272762 -2.017167  0.791396   
2020-01-17  0.815587  2.330721  0.521695 -2.266580 -0.583132  1.284555   
2020-01-16  1.029984  2.523432  0.131657  2.775084  0.328196  0.734990   
2020-01-15  1.912760  0.694877  0.400819 -1.318743  0.028547  1.705622   
2020-01-14  0.728383 -1.097548 -0.987925  0.441670  1.096681  0.369862   
2020-01-13 -0.281162  1.204194  2.094828  2.079725  1.153116  0.307399   
2020-01-10 -1.249422 -1.643864 -0.642398 -3.090448 -0.839485  0.489987   
2020-01-09  0.266790  2.383441  2.371871 -3.092551  0.831874  0.503158   
2020-01-08  0.407640 -0.870466  0.542185 -2.196812 -3.411334 -0.298858   
2020-01-07 -0.555942 -0.289316  0.424967  0.640819  0.112899  0.021352   
2020-01-06  0.523926 -0.432099 -0.044248 -0.889088  1.460481  0.332048   
2020-01-03 -1.219091 -1.018330 -2.223760 -0.158426  3.130538 -0.106998   
2020-01-02  0.103615  7.064980 -1.638368  2.502417  1.362072 -1.110994   
2019-12-31  0.069124  0.746924 -0.144478 -0.324150  0.997732  0.510475   
2019-12-30 -0.686499 -1.429190 -0.067943 -0.866822 -0.466446 -0.169869   
2019-12-27  0.137489 -0.965044 -0.249915 -0.192350 -1.467754  0.330209   
2019-12-26  0.000000  0.193382  0.438205 -0.351263  0.312314  0.042626   
2019-12-24 -0.080137  2.375715 -0.038275 -0.698036  0.523247  0.096000   
2019-12-23  0.796215  2.967157  0.059574  0.445959  3.161629 -1.211802   
2019-12-20 -0.789926  3.081952  0.832404  1.258338  1.805621  0.989678   
2019-12-19  0.483147  1.252955 -0.021449  0.747503 -2.105749  0.234667   
2019-12-18 -0.149322 -1.098901 -1.061076 -2.255340  0.603062  0.568548   
2019-12-17  0.763889  0.991736  0.499062 -1.006371  0.108359  0.204235   
2019-12-16  0.057904  2.916160  1.603536  0.473623  3.658537  1.064639   
2019-12-13  0.442015 -3.381075 -0.714286  0.095310 -1.672452  0.998464   
2019-12-12  1.248381  7.904738  1.263617  1.248653  2.889610 -1.096039   
2019-12-11  0.413907  0.076065  0.000000  0.709321 -0.210595  0.228410   
2019-12-10  0.822702  1.310044 -0.571874  0.714389 -0.032389  0.087089   
2019-12-09 -1.883482 -1.766339 -0.521484 -0.741476 -0.819146 -0.573655   

              906

In [100]:
# Converts investable dataframe into 3D tensor for input into RNN fitting
def formatX(investable_df):
    train_values = []
    for i in range(len(investable_df.index)):
        train_values.append(investable_df.iloc[i].values)
    train_values = np.array(train_values)
    train_values = np.reshape(train_values, (train_values.shape[0], 1, train_values.shape[1]))
    return train_values

In [101]:
formatX(get_investable(t, 80))

array([[[-3.22469983e+00, -7.80780781e+00, -3.70239636e+00, ...,
         -2.93484809e+00, -7.53082795e+00, -3.53029256e+00]],

       [[-1.14175899e+00, -6.96699843e+00, -1.68363352e-01, ...,
         -6.66837651e-01, -1.94328487e+00, -1.02035000e+00]],

       [[-1.00716204e+00, -2.76740238e+00, -1.64177938e-01, ...,
          6.10700155e-01,  2.87976962e-02, -1.63171470e+00]],

       ...,

       [[ 4.13907285e-01,  7.60649087e-02,  0.00000000e+00, ...,
         -9.65078102e-01,  1.70616114e-01,  6.83854202e-03]],

       [[ 8.22701800e-01,  1.31004367e+00, -5.71874188e-01, ...,
          1.46375934e+00, -3.21239607e-01,  1.05037662e+00]],

       [[-1.88348152e+00, -1.76633863e+00, -5.21484291e-01, ...,
         -2.63416552e+00, -1.18569695e+00, -1.03945839e+00]]])

In [102]:
# Formats output for a stock as a np array

def formatY(stock, t, n_rows):
    most_recent = t
    least_recent = t + pd.DateOffset(-n_rows)
    return returns[stock].loc[least_recent:most_recent].shift(-1).iloc[:-1].values[::-1]

In [106]:
# Creating a Simple RNN for an inputted stock

def get_model(stock, t, n_rows, investable_df):
    convertedX = convertToMatrix(investable_df)
    convertedY = formatY(stock, t, n_rows)
    
    model = Sequential()
    model.add(SimpleRNN(units=32, input_shape=(convertedX.shape[1], convertedX.shape[2]), activation="relu"))
    model.add(Dense(8, activation="relu")) 
    model.add(Dense(1))
    model.compile(loss='mean_squared_error', optimizer='rmsprop')
    
    model.fit(convertedX, convertedY, epochs=100, batch_size=16, verbose=2)
    
    return model

In [132]:
# Predicts stock price at a given date
import datetime

look_back = 80

def pred_date(stock, date):
    investable = get_investable(date, look_back)
    if stock not in investable.columns:
        print(stock + " is not in the investable universe")
        return
    if investable.shape[0] == 0:
        print("Investable universe is empty")
        return
    convertedX = formatX(investable.iloc[0:1])
    model = get_model(stock, date - datetime.timedelta(days=1), look_back, investable)
    return model.predict(convertedX)

In [133]:
pred_date("916328", t)

Epoch 1/100
4/4 - 1s - loss: 1.6840
Epoch 2/100
4/4 - 0s - loss: 0.6417
Epoch 3/100
4/4 - 0s - loss: 0.3371
Epoch 4/100
4/4 - 0s - loss: 0.3812
Epoch 5/100
4/4 - 0s - loss: 0.3912
Epoch 6/100
4/4 - 0s - loss: 1.0992
Epoch 7/100
4/4 - 0s - loss: 0.3982
Epoch 8/100
4/4 - 0s - loss: 0.1761
Epoch 9/100
4/4 - 0s - loss: 0.1473
Epoch 10/100
4/4 - 0s - loss: 0.1494
Epoch 11/100
4/4 - 0s - loss: 0.1484
Epoch 12/100
4/4 - 0s - loss: 0.1961
Epoch 13/100
4/4 - 0s - loss: 0.1008
Epoch 14/100
4/4 - 0s - loss: 0.1750
Epoch 15/100
4/4 - 0s - loss: 0.2110
Epoch 16/100
4/4 - 0s - loss: 0.1927
Epoch 17/100
4/4 - 0s - loss: 0.2014
Epoch 18/100
4/4 - 0s - loss: 0.1291
Epoch 19/100
4/4 - 0s - loss: 0.0896
Epoch 20/100
4/4 - 0s - loss: 0.0788
Epoch 21/100
4/4 - 0s - loss: 0.0784
Epoch 22/100
4/4 - 0s - loss: 0.1115
Epoch 23/100
4/4 - 0s - loss: 0.1444
Epoch 24/100
4/4 - 0s - loss: 0.2237
Epoch 25/100
4/4 - 0s - loss: 0.1554
Epoch 26/100
4/4 - 0s - loss: 0.1773
Epoch 27/100
4/4 - 0s - loss: 0.1515
Epoch 28/1

array([[-3.554593]], dtype=float32)

In [134]:
returns.loc[t, "916328"]

-4.135649296939626

In [105]:
convertedX = convertToMatrix(get_investable(t, 80))
model.predict(convertedX)

array([[-4.149425  ],
       [-3.1876523 ],
       [-1.0897539 ],
       [-0.8734021 ],
       [ 0.5606952 ],
       [-0.91085577],
       [ 1.1199747 ],
       [ 0.04846259],
       [-0.4195336 ],
       [ 1.0298836 ],
       [ 0.4942839 ],
       [-1.686663  ],
       [ 0.11253934],
       [ 1.0739907 ],
       [ 1.544517  ],
       [-0.01053615],
       [-2.222149  ],
       [-0.01053615],
       [-0.15079392],
       [-0.01053615],
       [-0.01053615],
       [-0.36814272],
       [-1.2524929 ],
       [ 2.3143144 ],
       [ 0.99493796],
       [ 1.8462325 ],
       [ 1.0259273 ],
       [ 1.9200814 ],
       [ 0.4288095 ],
       [-0.27803186],
       [-1.1819147 ],
       [ 1.0238563 ],
       [ 0.7016907 ],
       [-0.54143924],
       [ 0.48038727],
       [-1.3009133 ],
       [ 0.14288984],
       [-0.01053615],
       [-0.6819617 ],
       [ 0.15293474],
       [ 0.02162542],
       [ 0.1357847 ],
       [ 0.9609144 ],
       [-0.74740994],
       [ 0.4720417 ],
       [-0